name: wooyeon_flutter
description: A dating app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  eva_icons_flutter: ^3.1.0
  animated_bottom_navigation_bar: ^1.2.0
  provider: ^6.0.5
  get: ^4.6.5
  intl: ^0.18.1
  permission_handler: ^10.4.3
  smooth_page_indicator: ^1.1.0
  swipable_stack: ^2.0.0
  flutter_keyboard_visibility: ^5.4.1
  emoji_picker_flutter: ^1.6.1
  flutter_keyboard_size: ^1.0.1
  http: ^1.1.0
  http_parser: ^4.0.2
  flutter_secure_storage: ^8.0.0
  jwt_decode: ^0.3.1
  pin_input_text_field: ^4.5.1
  sms_autofill: ^2.3.0
  mobile_number: ^2.1.1
  loading_animation_widget: ^1.2.0+4
  shared_preferences: ^2.2.0
  textfield_tags: ^2.0.2
  image_picker: ^1.0.4
  image: ^4.0.17
  flutter_image_compress: ^2.0.4
  dio: ^5.3.2
  pointycastle: ^3.7.4
  stomp_dart_client: ^1.0.0
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/image/
  uses-material-design: true

fonts:
  - family: Pretendard
    fonts:
      - asset: assets/font/Pretendard-ExtraThin.otf
        weight: 100
      - asset: assets/font/Pretendard-Thin.otf
        weight: 200
      - asset: assets/font/Pretendard-Light.otf
        weight: 300
      - asset: assets/font/Pretendard-Regular.otf
        weight: 400
      - asset: assets/font/Pretendard-Medium.otf
        weight: 500
      - asset: assets/font/Pretendard-SemiBold.otf
        weight: 600
      - asset: assets/font/Pretendard-Bold.otf
        weight: 700
      - asset: assets/font/Pretendard-ExtraBold.otf
        weight: 800
      - asset: assets/font/Pretendard-Black.otf
        weight: 900